// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spnbyczjlhvfptvukthy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbmJ5Y3pqbGh2ZnB0dnVrdGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDY2NjYsImV4cCI6MjA3MTMyMjY2Nn0.c48iRw5_Fv4mBJum6nqiuQApy0aCX_SwZf14qj5dAy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});